name: Publish gh pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # configure the environment
    - uses: actions/checkout@v2
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo install trunk
    - run: trunk build --release --public-url number-reversi

    # deploy for github.io
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
